services:
  db-postgres: # 5432 default
    image: postgres:16
    environment:
      - POSTGRES_DB=dealer_db
      - POSTGRES_USER=autoshop-user
      - POSTGRES_PASSWORD=BrollyV543
    # volumes:
    #   - ./postgres_db_data:/var/lib/postgresql/data/
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autoshop-user -d dealer_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/

volumes:
  postgres_db_data: