"""create CarRent

Revision ID: c92b8ae09e03
Revises: 4211a3654bf5
Create Date: 2025-03-25 20:10:25.529143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92b8ae09e03'
down_revision = '4211a3654bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('rent_start', sa.DateTime(), nullable=True),
    sa.Column('rent_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'COMPLETED', name='rentstatus'), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_rent')
    # ### end Alembic commands ###
